/**
 * ByteFlow Configuration & SDK — UI GEN 2.0
 *
 * v2 generated apps authenticate with the account-level **ByteFlow API key**
 * (the keys managed in the ByteFlow profile "API Keys" tab). The key is
 * exchanged at runtime for a short-lived WebSocket session token — it is never
 * sent to ByteFlow's namespaces directly.
 *
 * The key is read from `VITE_BYTEFLOW_API_KEY` (a gitignored `.env.local`
 * written at project-creation time, and the same file the secrets-management
 * panel manages), so it is NOT committed in this source file. Note: Vite
 * inlines `VITE_*` vars into the built bundle, so the key is still public in the
 * shipped app — `.env.local` keeps it out of git/source, not out of the client.
 * Revoke from the profile if it leaks.
 *
 * The `BYTEFLOW_CONFIG` object below is rewritten at project-creation time by
 * the backend (`inject_vite_react_config_v2`) — everything between the
 * BYTEFLOW_CONFIG_START / BYTEFLOW_CONFIG_END sentinels is replaced. The SDK
 * functions are NOT regenerated, so this file is the single source of truth
 * for the SDK contract.
 */

// Node data structure including config for parameter overrides
export interface WorkflowNodeData {
  label?: string;
  config?: Record<string, any>;
  connectorType?: string;
  [key: string]: any;
}

export interface WorkflowNode {
  id: string;
  type: string;
  name?: string;
  data?: WorkflowNodeData;
  position?: { x: number; y: number };
}

export interface WorkflowEdge {
  id?: string;
  source: string;
  target: string;
  sourceHandle?: string;
  targetHandle?: string;
}

// Input schema field definition for parameter overrides
export interface InputSchemaField {
  nodeId: string;
  nodeLabel: string;
  field: string;
  label: string;
  type: 'string' | 'number' | 'boolean' | 'select' | 'multiline';
  defaultValue?: any;
  options?: string[];  // For select type
  description?: string;
}

export interface InputSchema {
  version: string;
  fields: InputSchemaField[];
}

// Stored backend schemas use snake_case and may carry extra form metadata.
// Public accessors below normalize these records to InputSchemaField.
export interface RawInputSchema {
  version: string;
  fields: Array<InputSchemaField | Record<string, unknown>>;
  [key: string]: unknown;
}

// Server-derived capability flags injected into BYTEFLOW_CONFIG. Only the fields
// that can't be cheaply derived client-side live here; getCapabilities(workflowId) composes
// the rest (hasChat, hasFileUpload, inputFields) from existing config.
export interface CapabilityFlags {
  schedulable: boolean;             // safe to expose a "run on a schedule" control
  hasHITLAgents: boolean;           // has agent nodes that may ask the user mid-run
  specializedAgentNodes: string[];  // node ids that stream rich agentProgressData
}

// The full capability manifest the generated app reads to decide which workflow
// surfaces to build. See the byteflow-workflow-ui skill (capability-manifest.md).
export interface Capabilities extends CapabilityFlags {
  hasChat: boolean;                 // workflow has a chat_trigger → build a chat UI
  hasFileUpload: boolean;           // workflow has file_upload node(s)
  inputFields: InputSchemaField[];  // overridable params → build a run form
}

// Baked (project-creation time) snapshot of a file_upload node. Initial paint
// only — the live state comes from getFileUploadNodes(workflowId).
export interface FileUploadNodeConfig {
  nodeId: string;
  label: string;
  accept: string;        // comma-separated extension list for <input accept=…>
  multiple: boolean;     // node currently holds a folder upload
  currentFile: { filename: string; size: number; fileType: string } | null;
}

export interface ByteflowConfig {
  projectId: string;
  workflowId: string;
  workflowName: string;
  apiKey: string;        // Account-level ByteFlow API key (from VITE_BYTEFLOW_API_KEY) — exchanged for a short-lived WS token
  apiUrl: string;        // Backend URL for token exchange, execution, and scheduling
  generationVersion: 'v2';
  nodes: WorkflowNode[];
  edges: WorkflowEdge[];
  hasChatTrigger: boolean;
  fileUploadNodes: FileUploadNodeConfig[];
  inputSchema: RawInputSchema;
  capabilities: CapabilityFlags;
}

// <BYTEFLOW_CONFIG_START> — generated by inject_vite_react_config_v2
export const BYTEFLOW_CONFIG: ByteflowConfig = {
  projectId: "4985c041",
  workflowId: "b8F_4nKA6Svfl9Vz3hB3",
  workflowName: "live",
  apiKey: import.meta.env.VITE_BYTEFLOW_API_KEY || '',
  apiUrl: "https://app.byteflow.bot",
  generationVersion: 'v2',
  nodes: [
  {
    "id": "mcp_agent_1788971702594",
    "type": "mcp_agent",
    "name": "Super Agent"
  },
  {
    "id": "shopify_mcp_tools_1789040489359",
    "type": "tools_module",
    "name": "Shopify MCP"
  },
  {
    "id": "manual_trigger_1791060273446",
    "type": "manual_trigger",
    "name": "Manual Trigger"
  }
],
  edges: [
  {
    "source": "mcp_agent_1788971702594",
    "target": "shopify_mcp_tools_1789040489359",
    "sourceHandle": "submodule-output",
    "targetHandle": "input"
  },
  {
    "source": "manual_trigger_1791060273446",
    "target": "mcp_agent_1788971702594",
    "sourceHandle": "output",
    "targetHandle": "input"
  }
],
  hasChatTrigger: false,
  fileUploadNodes: [],
  inputSchema: {
  "fields": [
    {
      "label": "Super Agent: Prompt",
      "node_id": "mcp_agent_1788971702594",
      "field_id": "mcp_agent_1788971702594.prompt",
      "is_input": false,
      "required": false,
      "field_path": "prompt",
      "field_type": "textarea",
      "validation": {},
      "description": "Override prompt for Super Agent",
      "default_value": "You are the AI Shopping Assistant for a Shopify store. You are a friendly, professional, human-like customer support assistant that helps customers before, during, and after their purchase.\r\n\r\nYour job is to resolve customer queries end-to-end while creating a smooth shopping experience. Always speak conversationally, keep responses concise unless the customer asks for more detail, and maintain a warm, helpful tone.\r\n\r\n## Core Responsibilities\r\n\r\nYou can assist customers with:\r\n\r\n* Order tracking and shipment status.\r\n* Product recommendations and product information.\r\n* Product catalog search and comparisons.\r\n* Returns, refunds, exchanges, and cancellations.\r\n* Order modifications (when allowed by store policy).\r\n* Payments, discounts, gift cards, and coupons.\r\n* Shipping information, delivery timelines, and availability.\r\n* Creating and managing customer support tickets.\r\n* Frequently asked questions about the store and policies.\r\n\r\nBehavior\r\n\r\n* Greet customers naturally and introduce yourself only once.\r\n* Understand the customer's intent before responding.\r\n* Ask for missing information only when necessary (order number, email, phone number, etc.).\r\n* Use connected Shopify tools and MCPs to retrieve live information instead of making assumptions.\r\n* Never invent order statuses, tracking updates, product availability, pricing, or refund information.\r\n* If information is unavailable, say so honestly and offer the next best action.\r\n\r\nCapabilities\r\n\r\n1. Order Tracking\r\n\r\nWhen a customer asks about an order:\r\n\r\n* Request the order number or registered email if needed.\r\n* Retrieve the live order status.\r\n* Provide shipment stage, courier, tracking number, estimated delivery date, and tracking updates.\r\n* If delayed, explain the current status and offer to create a support ticket if needed.\r\n\r\n2. Returns & Refunds\r\n\r\nHelp customers:\r\n\r\n* Check whether an order is eligible for return or exchange.\r\n* Explain the return policy clearly.\r\n* Initiate return or refund workflows through connected tools.\r\n* Inform customers about refund timelines and payment method.\r\n* Provide return instructions and pickup details when available.\r\n\r\n3. Product Support\r\n\r\nAnswer questions about:\r\n\r\n* Product specifications.\r\n* Sizes, colors, materials, compatibility, dimensions, and variants.\r\n* Availability and stock status.\r\n* Pricing and ongoing offers.\r\n* Compare products when requested.\r\n* Recommend products based on customer needs without being overly sales-oriented.\r\n\r\n4. Catalog Assistant\r\n\r\nSearch the Shopify catalog to:\r\n\r\n* Find products matching customer requests.\r\n* Suggest alternatives if an item is unavailable.\r\n* Filter by category, price, color, brand, or collection.\r\n* Highlight key product features.\r\n\r\n5. Customer Support Ticketing\r\n\r\nCreate a ticket whenever:\r\n\r\n* An issue cannot be resolved immediately.\r\n* The customer requests human assistance.\r\n* There is a damaged, missing, or incorrect item.\r\n* Delivery problems require escalation.\r\n\r\nEach ticket should include:\r\n\r\n* Customer name.\r\n* Contact details.\r\n* Order number.\r\n* Issue category.\r\n* Issue summary.\r\n* Priority level.\r\n* Timestamp.\r\n\r\nAfter creating a ticket, provide the ticket ID and explain the expected next steps.\r\n\r\nResponse Guidelines\r\n\r\n* Be empathetic for complaints or delivery issues.\r\n* Never blame the customer.\r\n* Confirm actions before making irreversible changes like cancellations or refunds.\r\n* Keep responses short for voice/video interactions.\r\n* If multiple questions are asked, answer them one by one in a logical order.\r\n\r\nEscalation Rules\r\n\r\nEscalate to a human agent if:\r\n\r\n* The customer requests a human.\r\n* Identity verification fails.\r\n* The issue involves fraud, payment disputes, or account security.\r\n* Backend tools cannot complete the requested action.\r\n* The customer is frustrated after repeated unsuccessful attempts.\r\n\r\nBefore escalating, summarize the conversation so the customer does not need to repeat themselves.\r\n\r\nTool Usage\r\n\r\nAlways use connected Shopify MCPs and available Byteflow connectors for:\r\n\r\n* Order lookup.\r\n* Tracking information.\r\n* Customer profile retrieval.\r\n* Product catalog search.\r\n* Inventory lookup.\r\n* Return/refund initiation.\r\n* Ticket creation.\r\n\r\nNever fabricate tool outputs.\r\n\r\nPersona\r\n\r\nYou are calm, confident, and customer-first. Your goal is to help customers complete their shopping journey quickly while providing accurate information and a premium support experience.\r\n\n"
    },
    {
      "label": "Super Agent: Timeout",
      "node_id": "mcp_agent_1788971702594",
      "field_id": "mcp_agent_1788971702594.timeout",
      "is_input": false,
      "required": false,
      "field_path": "timeout",
      "field_type": "number",
      "validation": {},
      "description": "Override timeout for Super Agent",
      "default_value": 600
    },
    {
      "label": "Super Agent: Connectorid",
      "node_id": "mcp_agent_1788971702594",
      "field_id": "mcp_agent_1788971702594.connectorId",
      "is_input": false,
      "required": false,
      "field_path": "connectorId",
      "field_type": "string",
      "validation": {},
      "description": "Override connectorid for Super Agent",
      "default_value": "shopify_mcp_tools"
    },
    {
      "label": "Super Agent: Heartbeat Enabled",
      "node_id": "mcp_agent_1788971702594",
      "field_id": "mcp_agent_1788971702594.heartbeat_enabled",
      "is_input": false,
      "required": false,
      "field_path": "heartbeat_enabled",
      "field_type": "boolean",
      "validation": {},
      "description": "Override heartbeat enabled for Super Agent",
      "default_value": false
    },
    {
      "label": "Super Agent: Guardrails Enabled",
      "node_id": "mcp_agent_1788971702594",
      "field_id": "mcp_agent_1788971702594.guardrails_enabled",
      "is_input": false,
      "required": false,
      "field_path": "guardrails_enabled",
      "field_type": "boolean",
      "validation": {},
      "description": "Override guardrails enabled for Super Agent",
      "default_value": false
    },
    {
      "label": "Super Agent: System Prompt",
      "node_id": "mcp_agent_1788971702594",
      "field_id": "mcp_agent_1788971702594.system_prompt",
      "is_input": false,
      "required": false,
      "field_path": "system_prompt",
      "field_type": "textarea",
      "validation": {},
      "description": "Override system prompt for Super Agent",
      "default_value": ""
    },
    {
      "label": "Message",
      "node_id": "manual_trigger_1791060273446",
      "field_id": "input.message",
      "is_input": true,
      "required": false,
      "field_path": "message",
      "field_type": "textarea",
      "validation": {},
      "description": "Input message for the workflow",
      "default_value": null
    }
  ],
  "version": "1.0"
},
  capabilities: {
  "schedulable": true,
  "hasHITLAgents": true,
  "specializedAgentNodes": [
    "mcp_agent_1788971702594"
  ]
},
};
// <BYTEFLOW_CONFIG_END>

const linkedWorkflows = new Map<string, ByteflowConfig>();

/** Register only server-authorized, sanitized project workflow snapshots. */
export function registerWorkflowConfigs(configs: Array<Omit<ByteflowConfig, 'apiKey' | 'apiUrl' | 'projectId' | 'generationVersion'>>): void {
  linkedWorkflows.clear();
  // workflows.json is agent-editable; a non-array (e.g. a keyed object) must
  // not crash the whole app at import time.
  const list = Array.isArray(configs)
    ? configs
    : configs && typeof configs === 'object' ? Object.values(configs) : [];
  for (const config of list) {
    linkedWorkflows.set(config.workflowId, { ...config,
      apiKey: BYTEFLOW_CONFIG.apiKey, apiUrl: BYTEFLOW_CONFIG.apiUrl,
      projectId: BYTEFLOW_CONFIG.projectId, generationVersion: 'v2' });
  }
}

export function getByteflowConfig(workflowId?: string): ByteflowConfig {
  if (!workflowId) return BYTEFLOW_CONFIG;
  const config = linkedWorkflows.get(workflowId);
  if (config) return config;
  if (workflowId === BYTEFLOW_CONFIG.workflowId) return BYTEFLOW_CONFIG;
  throw new Error(`Unavailable workflow: ${workflowId}`);
}

export function getApiUrl(): string {
  return BYTEFLOW_CONFIG.apiUrl;
}

export function getWorkflowNodes(workflowId?: string): WorkflowNode[] {
  return getByteflowConfig(workflowId).nodes || [];
}

export function getWorkflowEdges(workflowId?: string): WorkflowEdge[] {
  return getByteflowConfig(workflowId).edges || [];
}

// Returns the schema with fields NORMALIZED to the camelCase contract — same
// as getInputSchemaFields(workflowId). The raw BYTEFLOW_CONFIG.inputSchema may carry the
// backend's snake_case shape; a form built from the raw accessor would compose
// "undefined.undefined" override keys.
export function getInputSchema(workflowId?: string): InputSchema {
  return {
    ...(getByteflowConfig(workflowId).inputSchema || { version: '1.0', fields: [] }),
    fields: getInputSchemaFields(workflowId),
  };
}

// The backend (input_schema_generator.py) emits schema fields in snake_case
// (node_id / field_path / field_type / default_value), but the InputSchemaField
// contract — and every generated run form — reads camelCase (nodeId / field /
// type / defaultValue). Without this normalization the app reads `undefined` for
// nodeId+field, so every override key collapses to "undefined.undefined", the
// backend drops it, and the run falls back to the workflow's saved defaults
// (e.g. an empty prompt → "MCP Agent node requires a prompt"). Tolerant of BOTH
// shapes so it keeps working whichever casing the backend sends.
function normalizeFieldType(t: unknown): InputSchemaField['type'] {
  switch (t) {
    case 'textarea':
    case 'multiline':
      return 'multiline';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'select':
      return 'select';
    case 'string':
      return 'string';
    default:
      return 'string';
  }
}

function normalizeInputSchemaField(f: any): InputSchemaField {
  const nodeId = f?.nodeId ?? f?.node_id ?? '';
  let field = f?.field ?? f?.field_path;
  if ((field === undefined || field === null) && typeof f?.field_id === 'string') {
    // field_id is `${nodeId}.${field}` — strip the node prefix when present.
    field = nodeId && f.field_id.startsWith(`${nodeId}.`)
      ? f.field_id.slice(nodeId.length + 1)
      : f.field_id;
  }
  const options = Array.isArray(f?.options) ? (f.options as string[]) : undefined;
  let type = normalizeFieldType(f?.type ?? f?.field_type);
  // A 'select' with no options can't render a usable dropdown (the backend emits
  // e.g. a "model" field as select but supplies no options) — fall back to a
  // plain text input so the field still works.
  if (type === 'select' && (!options || options.length === 0)) type = 'string';
  return {
    nodeId,
    nodeLabel: f?.nodeLabel ?? f?.node_label ?? '',
    field: field ?? '',
    label: f?.label ?? '',
    type,
    defaultValue: f?.defaultValue ?? f?.default_value ?? undefined,
    options,
    description: f?.description,
  };
}

export function getInputSchemaFields(workflowId?: string): InputSchemaField[] {
  return (getByteflowConfig(workflowId).inputSchema?.fields || []).map(normalizeInputSchemaField);
}

// Default parameter overrides, keyed `nodeId.field` (matches the backend resolver).
export function getDefaultParameterValues(workflowId?: string): Record<string, any> {
  const defaults: Record<string, any> = {};
  for (const field of getInputSchemaFields(workflowId)) {
    if (field.defaultValue !== undefined && field.defaultValue !== null) {
      defaults[`${field.nodeId}.${field.field}`] = field.defaultValue;
    }
  }
  return defaults;
}

// Trigger nodes (manual_trigger, chat_trigger, ...) do NOT read their value from
// saved config — it's supplied LIVE per run via `input_data`. Since
// parameter_overrides only patches config, a trigger field left there is silently
// dropped and the run uses the workflow's saved default (e.g. an empty prompt →
// "MCP Agent node requires a prompt or input from previous node"). splitRunInputs
// routes a collected `nodeId.field` value map accordingly: trigger-node fields go
// to input_data (keyed by the bare field name), everything else stays in
// parameter_overrides. executeWorkflow() applies this automatically, so a run
// form can simply pass all collected field values as its first argument.
function isTriggerNodeType(nodeType: string | undefined): boolean {
  return !!nodeType && nodeType.toLowerCase().includes('trigger');
}

// Every registered node type whose primary "task" field is config.prompt —
// every handler in backend/registry.py mapped to TurboAgentHandler,
// MCPAgentHandler, ChatAgentHandler, SpecializedAgentHandler,
// CustomAgentHandler, or FlashAgentHandler, confirmed against each one's
// execute() (Sep 2026 audit). NOTE: "specialized_agent" is not itself a real
// node type — SpecializedAgentHandler is registered under 12 separate
// connector ids (the document/dev/creative/enterprise specialists below);
// an earlier version of this set used the fictional single name and silently
// excluded all 12, plus custom_specialized_agent and flash_agent.
// Their own connector copy says an EMPTY prompt means "use input from the
// previous node" — but the handlers only ever honor that when the field is
// truly empty. A NON-empty saved prompt (leftover test text from building the
// workflow, an old task nobody cleared) wins outright over whatever a
// connected trigger sends. Routing the value through the trigger's input_data
// doesn't help in that case — the agent never even looks at it. Live-reported:
// a generated app's override reached the trigger correctly but the connected
// Super Agent still ran its stale saved prompt.
const AGENT_PROMPT_NODE_TYPES = new Set([
  'ai_agent', 'mcp_agent', 'chat_agent',
  // Specialized Agents (Document Skills)
  'excel_expert', 'pdf_specialist', 'powerpoint_designer', 'word_document_pro',
  // Specialized Agents (Development & Technical)
  'web_builder', 'mcp_developer',
  // Specialized Agents (Creative & Design)
  'visual_artist', 'canvas_designer', 'gif_creator',
  // Specialized Agents (Enterprise & Communication)
  'brand_specialist', 'communications_writer', 'theme_designer',
  // Custom + Flash
  'custom_specialized_agent', 'flash_agent',
]);
// Trigger field names that actually carry "the message" — restricts the
// direct-to-agent targeting below to fields that are plausibly a task/prompt,
// not e.g. a trigger's unrelated settings field.
const MESSAGE_LIKE_FIELDS = new Set(['message', 'prompt', 'initial_message', 'input_data', 'text', 'content']);

export function splitRunInputs(
  values: Record<string, unknown>,
  extraInputData: Record<string, unknown> = {},
  workflowId?: string,
  configOverride?: ByteflowConfig,
): { parameterOverrides: Record<string, unknown>; inputData: Record<string, unknown> } {
  const nodes = configOverride?.nodes || getWorkflowNodes(workflowId);
  const edges = configOverride?.edges || getWorkflowEdges(workflowId);
  const nodeTypeById: Record<string, string> = {};
  for (const n of nodes) nodeTypeById[n.id] = n.type;

  const parameterOverrides: Record<string, unknown> = {};
  const inputData: Record<string, unknown> = { ...extraInputData };
  for (const [key, value] of Object.entries(values || {})) {
    if (value === undefined) continue;
    const dot = key.indexOf('.');
    const nodeId = dot === -1 ? key : key.slice(0, dot);
    const field = dot === -1 ? key : key.slice(dot + 1);
    if (isTriggerNodeType(nodeTypeById[nodeId])) {
      // A trigger's message only matters through whatever actually consumes
      // it. When that's a directly-connected agent, target its OWN prompt
      // field via parameter_overrides — the value its handler actually reads
      // (config.get("prompt")), which wins outright regardless of what was
      // saved there. Routing through the trigger's input_data too would be
      // dead weight: the agent doesn't consult it once its own config.prompt
      // is set. Only fall back to input_data when nothing downstream needs
      // the value this way (e.g. the trigger feeds a non-agent node).
      const connectedAgentIds = MESSAGE_LIKE_FIELDS.has(field)
        ? edges
            .filter((e) => e.source === nodeId && AGENT_PROMPT_NODE_TYPES.has(nodeTypeById[e.target] || ''))
            .map((e) => e.target)
        : [];
      if (connectedAgentIds.length > 0) {
        for (const agentId of connectedAgentIds) {
          parameterOverrides[`${agentId}.prompt`] = value;
        }
      } else {
        inputData[field] = value;
      }
    } else {
      parameterOverrides[key] = value;
    }
  }
  return { parameterOverrides, inputData };
}

// Read a node's configured value by nodeId + field.
export function getNodeConfigValue(nodeId: string, field: string, workflowId?: string): any {
  const node = getWorkflowNodes(workflowId).find((n) => n.id === nodeId);
  return node?.data?.config?.[field];
}

/**
 * The capability manifest for THIS workflow — read it first and build only the
 * surfaces it says exist (chat vs run form vs schedule vs file upload vs HITL).
 * Replaces the old hardcoded "if hasChatTrigger render ChatInterface" branch.
 *
 * Server-derived flags (schedulable, hasHITLAgents, specializedAgentNodes) come
 * from the injected config; the rest are composed from existing config fields,
 * with safe fallbacks so older injected configs (pre-capabilities) still work.
 *
 * See the byteflow-workflow-ui skill, references/capability-manifest.md.
 */
export function getCapabilities(workflowId?: string): Capabilities {
  const c = getByteflowConfig(workflowId);
  const injected: CapabilityFlags = c.capabilities || {
    schedulable: !c.hasChatTrigger,
    hasHITLAgents: false,
    specializedAgentNodes: [],
  };
  return {
    hasChat: !!c.hasChatTrigger,
    hasFileUpload: (c.fileUploadNodes?.length || 0) > 0,
    inputFields: getInputSchemaFields(workflowId),
    schedulable: injected.schedulable,
    hasHITLAgents: injected.hasHITLAgents,
    specializedAgentNodes: injected.specializedAgentNodes || [],
  };
}

/* ============================ Auth ============================ */

export type ByteflowAuthErrorKind = 'revoked' | 'invalid' | 'wallet_empty' | 'unknown';

/**
 * Raised when the embedded ByteFlow API key cannot be exchanged for a session
 * token. `userMessage` is safe to render directly to the end user.
 */
export class ByteflowAuthError extends Error {
  kind: ByteflowAuthErrorKind;
  userMessage: string;
  status?: number;

  constructor(kind: ByteflowAuthErrorKind, status?: number) {
    const userMessage =
      kind === 'revoked' || kind === 'invalid'
        ? "This app's API key is no longer valid. Please contact the app owner to restore access."
        : kind === 'wallet_empty'
        ? "The app owner's ByteFlow account is out of credits. Please contact the app owner."
        : 'Could not connect to ByteFlow. Please try again shortly.';
    super(userMessage);
    this.name = 'ByteflowAuthError';
    this.kind = kind;
    this.userMessage = userMessage;
    this.status = status;
  }
}

type AuthErrorListener = (err: ByteflowAuthError) => void;
const authErrorListeners = new Set<AuthErrorListener>();

/**
 * Subscribe to ByteFlow auth failures (revoked / invalid key, empty wallet).
 * Returns an unsubscribe function. Use this to show a clear message to the user
 * instead of a silent connection failure.
 */
export function onByteflowAuthError(listener: AuthErrorListener): () => void {
  authErrorListeners.add(listener);
  return () => authErrorListeners.delete(listener);
}

function emitAuthError(err: ByteflowAuthError): void {
  for (const listener of authErrorListeners) {
    try {
      listener(err);
    } catch {
      /* listener errors must not break the auth flow */
    }
  }
}

function authErrorKindFromStatus(status: number): ByteflowAuthErrorKind {
  if (status === 402) return 'wallet_empty';
  if (status === 401) return 'invalid';
  if (status === 403) return 'revoked';
  return 'unknown';
}

/**
 * Exchange the embedded ByteFlow API key for a short-lived WebSocket session
 * token (POST /api/ui/ws/auth). Shared by the Socket.IO hook and the HTTP SDK.
 *
 * Throws `ByteflowAuthError` (and notifies `onByteflowAuthError` listeners) on
 * a revoked / invalid key or an empty wallet.
 */
export async function exchangeForSessionToken(): Promise<string> {
  const config = getByteflowConfig();
  let res: Response;
  try {
    res = await fetch(`${config.apiUrl}/api/ui/ws/auth`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ projectId: config.projectId, apiKey: config.apiKey }),
    });
  } catch (e) {
    // Network error — transient, not an auth failure.
    throw new ByteflowAuthError('unknown');
  }

  if (!res.ok) {
    const kind = authErrorKindFromStatus(res.status);
    const err = new ByteflowAuthError(kind, res.status);
    emitAuthError(err);
    throw err;
  }

  const { token } = await res.json();
  return token as string;
}

/* ======================= Execution channel ======================= */

/**
 * Generate a fresh execution id. UI GEN 2.0 routes each workflow run on its own
 * `execution:{id}` channel so concurrent runs do not cross-talk (Phase 3).
 */
export function newExecutionId(): string {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID();
  }
  return `exec_${Date.now()}_${Math.random().toString(36).slice(2, 10)}`;
}

/** The Socket.IO room name for a given execution id. */
export function getExecutionChannel(executionId: string): string {
  return `execution:${executionId}`;
}

/** Action instances never consume another invocation's progress or results. */
export function acceptsActionEvent(channel: string, executionId: string | null, event: Record<string, unknown>): boolean {
  if (!channel.startsWith('action_')) return true;
  if (['connected', 'disconnected'].includes(String(event.type))) return true;
  if (!executionId) return false;
  const scopedChannel = String(event.channel_id || '');
  const marker = scopedChannel.indexOf(EXEC_CHANNEL_MARKER);
  const eventId = String(event.execution_id || event.executionId ||
    (marker >= 0 ? scopedChannel.slice(marker + EXEC_CHANNEL_MARKER.length) : ''));
  if (eventId) return eventId === executionId;
  return false;
}

/**
 * Marker that scopes a channel_id to a single run. The backend derives the
 * dedicated `execution:{id}` Socket.IO room from the suffix while the base
 * portion is still used for per-card client-side filtering. Must match
 * EXEC_CHANNEL_MARKER in backend/services/event_publisher.py.
 */
export const EXEC_CHANNEL_MARKER = '~exec~';

/** Scope a base channel ("ui_{projectId}" or a per-card channel) to one run. */
export function withExecutionScope(baseChannel: string, executionId: string): string {
  return `${baseChannel}${EXEC_CHANNEL_MARKER}${executionId}`;
}

/** Strip the per-execution suffix, returning the base channel for filtering. */
export function baseChannelOf(channelId: string): string {
  const i = channelId.indexOf(EXEC_CHANNEL_MARKER);
  return i === -1 ? channelId : channelId.slice(0, i);
}

/* ======================== HTTP SDK ======================== */

/**
 * Execute the workflow over HTTP (alternative to the live WebSocket path).
 * Authenticates with the embedded ByteFlow API key, same as the hook's
 * executeWorkflow — the public endpoint validates the key directly.
 *
 * @param inputs       Parameter overrides, keyed `nodeId.field`.
 * @param executionId  Optional caller-supplied execution id (else generated).
 */
export async function executeWorkflowApi(
  inputs?: Record<string, unknown>,
  executionId?: string,
  workflowId?: string,
): Promise<{ executionId: string; result: unknown }> {
  const config = getByteflowConfig(workflowId);
  const execId = executionId || newExecutionId();
  // Trigger fields (e.g. manual_trigger "message") must go to input_data, not
  // parameter_overrides (which only patches saved config) — splitRunInputs routes them.
  const routed = splitRunInputs(inputs || {}, {}, workflowId);

  const res = await fetch(`${config.apiUrl}/workflows/public/${config.workflowId}/execute`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${config.apiKey}`,
    },
    body: JSON.stringify({
      parameter_overrides: routed.parameterOverrides,
      input_data: routed.inputData,
      execution_id: execId,
    }),
  });

  if (!res.ok) {
    if (res.status === 401 || res.status === 402 || res.status === 403) {
      const err = new ByteflowAuthError(authErrorKindFromStatus(res.status), res.status);
      emitAuthError(err);
      throw err;
    }
    throw new Error(`Workflow execution failed: ${res.status} ${res.statusText}`);
  }
  return { executionId: execId, result: await res.json() };
}

/**
 * Extract the human-facing RESPONSE from a workflow run result.
 *
 * A run's raw result is a per-node JSON envelope (statuses, metadata, nested
 * node outputs). End users should see the final output text — never that
 * envelope. Pass either the HTTP result from executeWorkflowApi() or the
 * hook's `wf.result` / `wf.result.outputs`; returns the terminal output as a
 * string (markdown — render it with the app's markdown renderer, don't
 * JSON.stringify it), or null when the run produced no displayable output.
 */
export function extractWorkflowResponse(result: unknown): string | null {
  const asText = (v: unknown): string | null => {
    if (v === null || v === undefined) return null;
    if (typeof v === 'string') return v.trim() ? v : null;
    if (typeof v === 'number' || typeof v === 'boolean') return String(v);
    return null;
  };

  const fromNodeOutput = (v: unknown): string | null => {
    const direct = asText(v);
    if (direct !== null) return direct;
    if (typeof v !== 'object' || v === null) return null;
    const obj = v as Record<string, unknown>;
    // Common output envelopes, most specific first.
    for (const key of ['response', 'output', 'content', 'text', 'message', 'result', 'data']) {
      if (key in obj) {
        const nested = fromNodeOutput(obj[key]);
        if (nested !== null) return nested;
      }
    }
    return null;
  };

  if (result === null || result === undefined) return null;
  const direct = asText(result);
  if (direct !== null) return direct;
  if (typeof result !== 'object') return null;

  const envelope = result as Record<string, unknown>;
  // HTTP endpoint shape: { status, result: {...} } — unwrap once.
  const inner =
    envelope.results || envelope.outputs ||
    (typeof envelope.result === 'object' && envelope.result !== null
      ? ((envelope.result as Record<string, unknown>).results ||
         (envelope.result as Record<string, unknown>).outputs ||
         envelope.result)
      : envelope.result) ||
    envelope;

  const fromEnvelope = fromNodeOutput(inner);
  if (typeof inner !== 'object' || inner === null) return fromEnvelope;

  // Per-node map ({ [nodeId]: nodeResult }): take the LAST node that produced
  // displayable output — insertion order follows execution order.
  const nodeMap = inner as Record<string, unknown>;
  let last: string | null = null;
  for (const value of Object.values(nodeMap)) {
    const text = fromNodeOutput(value);
    if (text !== null) last = text;
  }
  return last ?? fromEnvelope;
}

export interface CreateScheduleParams {
  /** A cron expression, e.g. "0 9 * * *". Provide this OR intervalSeconds. */
  cron?: string;
  /** A fixed interval in seconds. Provide this OR cron. */
  intervalSeconds?: number;
  /** IANA timezone for cron schedules, e.g. "America/New_York". Defaults to UTC. */
  timezone?: string;
  /** Parameter overrides applied to every scheduled run, keyed `nodeId.field`. */
  parameterOverrides?: Record<string, unknown>;
  /** Optional human-readable schedule name. */
  name?: string;
}

/**
 * Create a recurring schedule for this app's workflow.
 *
 * Scheduled runs are unattended: the supplied field values are baked into every
 * fire. Trigger fields (e.g. a manual_trigger "message") are routed to
 * input_data so they actually hydrate each run; config fields stay in
 * parameter_overrides (the same split as a live run — see splitRunInputs).
 *
 * Authenticated with the embedded account-level ByteFlow key via the
 * Authorization header (the v2 auth the public schedule endpoint accepts).
 */
export async function createSchedule(params: CreateScheduleParams, workflowId?: string): Promise<unknown> {
  const config = getByteflowConfig(workflowId);

  // The endpoint expects schedule_type + schedule_value (not cron/interval_seconds).
  let schedule_type: 'cron' | 'interval';
  let schedule_value: string;
  if (params.cron) {
    schedule_type = 'cron';
    schedule_value = params.cron;
  } else if (params.intervalSeconds != null) {
    schedule_type = 'interval';
    schedule_value = `${params.intervalSeconds}s`;
  } else {
    throw new Error('createSchedule requires either `cron` or `intervalSeconds`');
  }

  // Route trigger-node fields to input_data (baked into every fire); config
  // fields stay in parameter_overrides.
  const { parameterOverrides, inputData } = splitRunInputs(params.parameterOverrides || {}, {}, workflowId);

  const res = await fetch(
    `${config.apiUrl}/workflows/public/${config.workflowId}/schedule`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${config.apiKey}`,
      },
      body: JSON.stringify({
        projectId: config.projectId,
        schedule_type,
        schedule_value,
        timezone: params.timezone || 'UTC',
        parameter_overrides: parameterOverrides,
        input_data: inputData,
        name: params.name,
        // Generated-app schedules are unattended — the agent must never block on
        // a human-in-the-loop prompt with no user present.
        disable_hitl: true,
      }),
    },
  );

  if (!res.ok) {
    if (res.status === 401 || res.status === 402 || res.status === 403) {
      const err = new ByteflowAuthError(authErrorKindFromStatus(res.status), res.status);
      emitAuthError(err);
      throw err;
    }
    throw new Error(`Schedule creation failed: ${res.status} ${res.statusText}`);
  }
  return res.json();
}

/* ===================== File-upload nodes ===================== */

/** Live (server-side) state of one file_upload node. */
export interface FileUploadNodeState {
  nodeId: string;
  label: string;
  accept: string;
  parseMode: string;
  currentFile: {
    filename: string;
    size: number;
    sizeFormatted: string;
    fileType: string;
  } | null;
  currentFolder: {
    fileCount: number;
    totalSize: number;
    files: { filename: string; size: number; fileType: string }[];
  } | null;
}

/** Baked snapshot of the workflow's file_upload nodes (initial paint only). */
export function getFileUploadNodesConfig(workflowId?: string): FileUploadNodeConfig[] {
  return getByteflowConfig(workflowId).fileUploadNodes || [];
}

function fileNodeAuthCheck(res: Response): void {
  if (res.status === 401 || res.status === 402 || res.status === 403) {
    const err = new ByteflowAuthError(authErrorKindFromStatus(res.status), res.status);
    emitAuthError(err);
    throw err;
  }
}

/**
 * Fetch the LIVE state of every file_upload node in the workflow.
 *
 * This is authoritative: a file replaced in the ByteFlow dashboard shows up
 * here, while the baked `getFileUploadNodesConfig(workflowId)` snapshot does not.
 * Call on mount and again after every `uploadFileToNode()`.
 */
export async function getFileUploadNodes(workflowId?: string): Promise<FileUploadNodeState[]> {
  const config = getByteflowConfig(workflowId);
  const res = await fetch(
    `${config.apiUrl}/workflows/public/${config.workflowId}/file-nodes`,
    { headers: { Authorization: `Bearer ${config.apiKey}` } },
  );
  if (!res.ok) {
    fileNodeAuthCheck(res);
    throw new Error(`Failed to load file-node state: ${res.status} ${res.statusText}`);
  }
  const body = await res.json();
  return (body.file_nodes || []).map((n: any): FileUploadNodeState => ({
    nodeId: n.node_id,
    label: n.label,
    accept: n.accept,
    parseMode: n.parse_mode,
    currentFile: n.current_file
      ? {
          filename: n.current_file.filename,
          size: n.current_file.size,
          sizeFormatted: n.current_file.size_formatted,
          fileType: n.current_file.file_type,
        }
      : null,
    currentFolder: n.current_folder
      ? {
          fileCount: n.current_folder.file_count,
          totalSize: n.current_folder.total_size,
          files: (n.current_folder.files || []).map((f: any) => ({
            filename: f.filename,
            size: f.size,
            fileType: f.file_type,
          })),
        }
      : null,
  }));
}

/**
 * Upload a file into a workflow file_upload node — and PERSIST it.
 *
 * The file is stored the same way the ByteFlow dashboard's uploader stores it
 * and written into the workflow itself, so the dashboard shows the new file
 * and every subsequent run (executeWorkflowApi, schedules) uses it. No
 * parameter overrides needed.
 *
 * Uses XHR so `onProgress` receives real upload progress (0–100).
 */
export function uploadFileToNode(
  nodeId: string,
  file: File,
  onProgress?: (percent: number) => void,
  workflowId?: string,
): Promise<{ filename: string; size: number; sizeFormatted: string; fileType: string }> {
  const config = getByteflowConfig(workflowId);
  const url = `${config.apiUrl}/workflows/public/${config.workflowId}/file-nodes/${nodeId}/upload`;

  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('POST', url);
    xhr.setRequestHeader('Authorization', `Bearer ${config.apiKey}`);

    xhr.upload.onprogress = (e) => {
      if (e.lengthComputable && onProgress) {
        onProgress(Math.round((e.loaded / e.total) * 100));
      }
    };

    xhr.onload = () => {
      if (xhr.status >= 200 && xhr.status < 300) {
        try {
          const body = JSON.parse(xhr.responseText);
          const f = body.file || {};
          resolve({
            filename: f.filename,
            size: f.size,
            sizeFormatted: f.size_formatted,
            fileType: f.file_type,
          });
        } catch {
          reject(new Error('Upload succeeded but the response could not be parsed'));
        }
        return;
      }
      if (xhr.status === 401 || xhr.status === 402 || xhr.status === 403) {
        const err = new ByteflowAuthError(authErrorKindFromStatus(xhr.status), xhr.status);
        emitAuthError(err);
        reject(err);
        return;
      }
      let detail = `${xhr.status} ${xhr.statusText}`;
      try {
        detail = JSON.parse(xhr.responseText)?.detail || detail;
      } catch {
        /* keep status text */
      }
      reject(new Error(`File upload failed: ${detail}`));
    };

    xhr.onerror = () => reject(new Error('File upload failed: network error'));

    const form = new FormData();
    form.append('file', file, file.name);
    xhr.send(form);
  });
}

export default {
  getByteflowConfig,
  getApiUrl,
  getWorkflowNodes,
  getWorkflowEdges,
  getInputSchema,
  getInputSchemaFields,
  getDefaultParameterValues,
  splitRunInputs,
  getNodeConfigValue,
  getCapabilities,
  exchangeForSessionToken,
  onByteflowAuthError,
  ByteflowAuthError,
  newExecutionId,
  getExecutionChannel,
  executeWorkflowApi,
  extractWorkflowResponse,
  createSchedule,
  getFileUploadNodesConfig,
  getFileUploadNodes,
  uploadFileToNode,
};
